

# This file was *autogenerated* from the file main.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_6 = Integer(6); _sage_const_3 = Integer(3); _sage_const_7 = Integer(7); _sage_const_8 = Integer(8); _sage_const_4 = Integer(4); _sage_const_101 = Integer(101); _sage_const_19 = Integer(19); _sage_const_12 = Integer(12); _sage_const_33 = Integer(33); _sage_const_40 = Integer(40); _sage_const_9 = Integer(9); _sage_const_15 = Integer(15); _sage_const_11 = Integer(11); _sage_const_100 = Integer(100); _sage_const_5000 = Integer(5000); _sage_const_10 = Integer(10); _sage_const_500 = Integer(500); _sage_const_200 = Integer(200); _sage_const_20 = Integer(20); _sage_const_5 = Integer(5); _sage_const_41 = Integer(41)
from sage.groups.perm_gps.permgroup import PermutationGroup
from sage.graphs.distances_all_pairs import diameter
import math
from sys import stdout

def is_good_transposition(p):
    n=len(p)
    sign = [len(i) for i in p.to_cycles()]
    sign.sort()
    return (sign[-_sage_const_1 ]==_sage_const_2  and sign.count(_sage_const_1 )==n-_sage_const_2  and any([len(i)==_sage_const_2  and math.gcd(i[_sage_const_1 ]-i[_sage_const_0 ],n)==_sage_const_1  for i in p.to_cycles()]))

def perm_pow(self,a):
        if(a==_sage_const_1 ): return self
        if(a==_sage_const_0 ): return Permutation(self.n)
        if(a%_sage_const_2 ==_sage_const_0 ):
            b=self**(a//_sage_const_2 )
            return b*b
        else:
            return self**(a-_sage_const_1 )*self

def signature(self):
    return list(sorted([len(i) for i in self.to_cycles()]))

def get_all_powers(self):
        perm = self
        perm *= perm
        powers = [self,perm]
        while True:
            perm*=self
            if tuple(self)==tuple(perm):
                break
            powers.append(perm)
        return powers
    


Permutation.__pow__ = perm_pow
Permutation.get_all_powers = get_all_powers
Permutation.signature = signature

def Prefix(n,k):
    l=[i+_sage_const_1  for i in range(n)]
    l=l[:k][::-_sage_const_1 ]+l[k:]
    return Permutation(list(tuple(l)))

def is_n2(p,n):
    return Prefix(n,n-_sage_const_2 ) == p

def arr_to_str(arr):
    return ''.join([str(i) for i in arr])

def get_all_combos(generators, combo_length) -> list[tuple[str,int,Permutation]]:
    sz = combo_length
    gen_n = len(generators)
    ans = []
    hashes = set()
    n = len(generators[_sage_const_0 ])
    for mask in range(gen_n**(sz)):
        inds = [(mask//(gen_n**i))%gen_n for i in range(sz)]
        prod = Prefix(n,_sage_const_1 ) # unit perm
        for ind in inds:
            prod *= generators[ind]

        if(tuple(prod) not in hashes):
            hashes.add(tuple(prod))
            ans.append((arr_to_str(inds),_sage_const_1 ,prod))
    return ans

def bake(generators, recipe):
    # print(generators[0],len(generators[0]))
    ans = Prefix(len(generators[_sage_const_0 ]),_sage_const_1 )
    for c in recipe:
        ans*=generators[int(c)]
    #print(ans)
    return ans

def verify(generators, ext_perms):
    for e_perm in ext_perms:
        # print(bake(generators,e_perm[0]))
        res1 = bake(generators,e_perm[_sage_const_0 ])**e_perm[_sage_const_1 ]
        # print("!", res1, e_perm)
        if(tuple(res1)!=tuple(e_perm[_sage_const_2 ])):
            print("BAD")
            print(e_perm)
            print(res1)
            exit(_sage_const_0 )

class BreakLoop(Exception):
    pass

def ext_perms_to_all_unique_powers(perms:list[tuple[str,int,Permutation]]) -> list[tuple[str,int,Permutation]]:
    s = set()
    ans = []
    for perm in perms:
        powers = perm[_sage_const_2 ].get_all_powers()
        for pwn,power in enumerate(powers):
            if tuple(power) not in s:
                s.add(tuple(power))
                ans.append((perm[_sage_const_0 ],pwn+_sage_const_1 ,power))
    return ans



def find_LR(n,pref_mx=_sage_const_0 ,pc_mx=_sage_const_6 ,suff_mx=_sage_const_0 ):
    """
    Given r2, rn. Try to find k-s where r2 + rk + rn give L or R in from below.
    Prefx + (PowerCombo)**q + suffix?
    """
    for k in range(_sage_const_2 ,n-_sage_const_1 ):
        # print('hey')
        generators = [Prefix(n,_sage_const_1 ) ,Prefix(n,k), Prefix(n,n-_sage_const_1 ), Prefix(n,n)]
        generators.append(bake(generators,'3212'))
        pref_combos = ext_perms_to_all_unique_powers(get_all_combos(generators, pref_mx))
        mid_combos = ext_perms_to_all_unique_powers(get_all_combos(generators, pc_mx))
        suff_combos = ext_perms_to_all_unique_powers(get_all_combos(generators, suff_mx))
        verify(generators,suff_combos)
        for p in pref_combos:
            for m in mid_combos:
                for s in suff_combos:
                    if is_good_transposition(p[_sage_const_2 ]*m[_sage_const_2 ]*s[_sage_const_2 ]) and p[_sage_const_1 ] == _sage_const_1  and s[_sage_const_1 ] == _sage_const_1  and m[_sage_const_1 ] == n-_sage_const_3 :
                        pp, mm, ss = bake(generators,p[_sage_const_0 ]),bake(generators,m[_sage_const_0 ]),bake(generators,s[_sage_const_0 ])
                        print(n,k,p[_sage_const_0 ],m[_sage_const_0 ],s[_sage_const_0 ], p[_sage_const_1 ], m[_sage_const_1 ], s[_sage_const_1 ])
                        return _sage_const_1 
    return _sage_const_0 

def find_all_ks_with_recipes(n,pref_mx=_sage_const_0 ,pc_mx=_sage_const_7 ,suff_mx=_sage_const_0 ):
    """
    Given r2, rn. Try to find k-s where r2 + rk + rn give L or R in from below.
    Prefx + (PowerCombo)**q + suffix?
    """
    for k in range(_sage_const_2 ,n-_sage_const_1 ):
        # print('hey')
        generators = [Prefix(n,_sage_const_1 ) ,Prefix(n,k), Prefix(n,n-_sage_const_1 ), Prefix(n,n)]
        generators.append(bake(generators,'2321'))
        generators.append(bake(generators,'43'))
        generators.append(bake(generators,'54'))
        mid_combos = ext_perms_to_all_unique_powers(get_all_combos(generators, pc_mx))
        try:
            for m in mid_combos:
                if is_good_transposition(m[_sage_const_2 ]):
                    print(n,k,m[_sage_const_0 ],m[_sage_const_1 ])
                    raise BreakLoop
        except BreakLoop:
            pass
        else:
            print(k,'not found')
    return _sage_const_0 

def find_all_ks_with_recipes_odd(n,pref_mx=_sage_const_0 ,pc_mx=_sage_const_8 ,suff_mx=_sage_const_0 ):
    """
    Given r2, rn. Try to find k-s where r2 + rk + rn give L or R in from below.
    Prefx + (PowerCombo)**q + suffix?
    """
    for k in range(_sage_const_6 ,n-_sage_const_4 ,_sage_const_2 ):
        # print('hey')
        generators = [Prefix(n,_sage_const_1 ) ,Prefix(n,k), Prefix(n,n-_sage_const_1 ), Prefix(n,n)]
        generators.append(bake(generators,'3212'))
        mid_combos = ext_perms_to_all_unique_powers(get_all_combos(generators, pc_mx))
        try:
            for m in mid_combos:
                if is_n2(m[_sage_const_2 ],n):
                    print(n,k,m[_sage_const_0 ],m[_sage_const_1 ])
                    raise BreakLoop
        except BreakLoop:
            pass
        else:
            print(k,'not found')
    return _sage_const_0 

def find_all_big_complements():
    for n in range(_sage_const_6 ,_sage_const_101 ):
        working = []
        for k in range(_sage_const_2 ,n-_sage_const_1 ):
            generators = [Prefix(n,k),Prefix(n,n-_sage_const_1 ),Prefix(n,n)]
            G = PermutationGroup(generators)
            Sn = SymmetricGroup(n)
            if(G.cardinality() == Sn.cardinality()):
                working.append(k)
        print(n,working)



def check_hyp_any_works():
    n=_sage_const_19 +_sage_const_4 *_sage_const_3 
    find_all_ks_with_recipes(n)

def check_hyp_2_works():
    n=_sage_const_12 
    find_all_ks_with_recipes_odd(n)

def find_rec_for_6(mx_len=_sage_const_6 ):
    for n in range(_sage_const_33 ,_sage_const_40 ,_sage_const_2 ):
        k = _sage_const_6 
        gens = [Prefix(n,_sage_const_1 ), Prefix(n,k), Prefix(n,n-_sage_const_1 ), Prefix(n,n)]
        #gens.append(bake(gens,'31'))
        gens.append(bake(gens,'32'))
        com = ext_perms_to_all_unique_powers(get_all_combos(gens,_sage_const_8 ))
        for c in com:
            if is_good_transposition(c[_sage_const_2 ]):
                print(n, c)
                #break
        else:
            print(n,'not found')

def check_recipe_for_6():
    k = _sage_const_6 
    for n in range(_sage_const_9 ,_sage_const_101 ,_sage_const_4 ):
        gens = [Prefix(n,_sage_const_1 ), Prefix(n,k), Prefix(n,n-_sage_const_1 ), Prefix(n,n)]
        gens.append(bake(gens,'32'))
        L, R = gens[_sage_const_2 ]*gens[_sage_const_3 ], gens[_sage_const_3 ]*gens[_sage_const_2 ]
        p1 = bake(gens,'14144123')
        print(n,[len(i) for i in p1.to_cycles()])
        print(n,[len(i) for i in (p1**((n-_sage_const_3 )//_sage_const_2 )).to_cycles()])
        #print(n,p1.to_cycles())
        #print((p1**(n-6-((n-1)//2-4))).to_cycles())
        p2 = gens[_sage_const_4 ]
        G = PermutationGroup([p1**(_sage_const_15 ),p2])
        Sn = SymmetricGroup(n)
        if(G.cardinality() == Sn.cardinality()):
            print(n, 'works')
        else:
            print(n, 'doesnt')


def compute_diameters():
    for n in range(_sage_const_9 ,_sage_const_11 ):
        candidate_names = ["2","n-3","4","6","n-4"]
        candidates = [Prefix(n,_sage_const_2 ),Prefix(n-_sage_const_3 ,_sage_const_2 ),Prefix(n,_sage_const_4 ),Prefix(n,_sage_const_6 ),Prefix(n,n-_sage_const_4 )]
        big_2 = [Prefix(n,n-_sage_const_1 )*Prefix(n,n),Prefix(n,n)*Prefix(n,n-_sage_const_1 )]
        for i,candidate in enumerate(candidates):
            gens = [candidate] + big_2
            G = PermutationGroup(gens)
            Sn = SymmetricGroup(n)
            if(Sn.cardinality() != G.cardinality()):
                print(n,candidate_names[i],'is bad')
                continue
            print(n, candidate_names[i], diameter(G.cayley_graph().to_undirected(), algorithm='multi-sweep'))
            sys.stdout.flush() 


from queue import Queue
import math
def is_power_good(p):
    n = len(p)
    signature = [len(i) for i in p.to_cycles()]
    if signature.count(_sage_const_2 ) == _sage_const_1  and all([i%_sage_const_2 ==_sage_const_1  or (i==_sage_const_2  and math.gcd(max(cyc[_sage_const_0 ],cyc[_sage_const_1 ])-min(cyc[_sage_const_0 ],cyc[_sage_const_1 ]),n)==_sage_const_1 ) for i,cyc in zip(signature,p.to_cycles())]):
        #print(p.to_cycles())
        return True
    else:
        return False


def find_shortest_good_shit(n):
    gens = [Prefix(n,_sage_const_6 ),Prefix(n,n-_sage_const_1 ),Prefix(n,n)]
    seen = set()
    q = Queue()
    q.put(('',Prefix(n,_sage_const_1 )))
    while(True):
        v = q.get()
        for i,g in enumerate(gens):
            to = v[_sage_const_1 ]*g
            if(to not in seen):
                seen.add(to)
                q.put((v[_sage_const_0 ]+str(i),to))
            if(is_power_good(to)):
                return (n,v[_sage_const_0 ]+str(i),to)
                #print(n,v[0]+str(i))
                #return

'''
13 : 010210212
20 : 01021021212
22 : 01201210212
24 : 01020121212
'''

def find_good_power(p):
    return math.prod([len(i) for i in p.to_cycles() if len(i)!=_sage_const_2 ])
    return math.lcm(*[len(i) for i in p.to_cycles() if len(i)!=_sage_const_2 ])

def make_pref_by_delta(n,delta):
    if(delta<_sage_const_0 ):
        return Prefix(n,n+delta)
    elif delta==_sage_const_0 :
        return Prefix(n,n)
    else:
        return Prefix(n,delta)

def check_recipes(delta,recipes,labels,nmin,nmax,nstep):
    ret = {}
    for n in range(nmin,nmax,nstep):
        gens = [make_pref_by_delta(n,delta),Prefix(n,n-_sage_const_1 ),Prefix(n,n)]
        results = []
        for ind,recipe in enumerate(recipes):
            res = bake(gens,recipe)
            if(not is_power_good(res)):
                continue
            results.append((labels[ind],find_good_power(res)))
            if(labels[ind] in ret):
                ret[labels[ind]].append(n)
            else:
                ret[labels[ind]] = [n]
        print(n,results)
    return ret

def find_shortest_recipes(delta,nmin,nmax,nstep):
    print("FUCK")
    seen_recipes = {}
    for n in range(nmin,nmax,nstep):
        gens = [make_pref_by_delta(n,delta),Prefix(n,n-_sage_const_1 ),Prefix(n,n)]
        try:
            for rec in seen_recipes.keys():
                if(is_power_good(bake(gens,rec))):
                    print(n, 'first_seen', seen_recipes[rec])
                    raise BreakLoop
        except:
            continue
        _,rec,perm = find_shortest_good_shit(n)
        if(rec not in seen_recipes):
            print(n,"NEW!",rec)
            seen_recipes[rec] = n
        else:
            print(n, 'first_seen', seen_recipes[rec])
    return seen_recipes


def is_power_good_nminus2(p):
    n = len(p)
    signature = [len(i) for i in p.to_cycles()]
    if signature.count(_sage_const_2 ) == _sage_const_1  and all([i%_sage_const_2 ==_sage_const_1  or (i==_sage_const_2  and max(cyc[_sage_const_0 ],cyc[_sage_const_1 ])-min(cyc[_sage_const_0 ],cyc[_sage_const_1 ])==_sage_const_2 ) for i,cyc in zip(signature,p.to_cycles())]):
        #print(p.to_cycles())
        return True
    else:
        return False

def find_shortest_good_shit_LR(gens,n,start=''):
    seen = set()
    q = Queue()
    q.put((start,bake(gens,start)))
    while(q.qsize() != _sage_const_0 ):
        v = q.get()
        if(is_power_good_nminus2(v[_sage_const_1 ])):
                return (n,v[_sage_const_0 ],v[_sage_const_1 ])
        for i,g in enumerate(gens):
            to = v[_sage_const_1 ]*g
            if(tuple(to) not in seen):
                seen.add(tuple(to))
                q.put((v[_sage_const_0 ]+str(i),to))
    return (-_sage_const_1 ,-_sage_const_1 ,-_sage_const_1 )

GLOBCNT=_sage_const_0 

def bfs(gens,start,checker):
    seen = set()
    q = Queue()
    q.put(("",start))
    global GLOBCNT
    while(q.qsize()!=_sage_const_0 ):
        v=q.get()
        '''
        GLOBCNT+=1
        if(GLOBCNT==10000):
            print(v[0],v[1].to_cycles())
            GLOBCNT=1
        '''
        if(checker(v[_sage_const_1 ])):
            return (v[_sage_const_0 ],v[_sage_const_1 ])
        for i,g in enumerate(gens):
            to=v[_sage_const_1 ]*g
            if(tuple(to) not in seen):
                seen.add(tuple(to))
                q.put((v[_sage_const_0 ]+str(i),to))
    return ("-",_sage_const_0 )

def find_shortest_recipes_general(deltas,checker,gen_recs=[],start_rec='',nmin=_sage_const_4 ,nmax=_sage_const_100 ,nstep=_sage_const_1 ):
    if len(gen_recs) != len(deltas):
        gen_recs=list(range(len(deltas)))
    
    seen_recipes = {}
    for n in range(nmin,nmax,nstep):
        basis = [make_pref_by_delta(n,i) for i in deltas]
        genss = [bake(basis,r) for r in gen_recs]
        try:
            for rec in seen_recipes.keys():
                if(checker(bake(genss,rec))):
                    print(n, 'first_seen', seen_recipes[rec])
                    raise BreakLoop
        except:
            continue
        rec,perm = bfs(genss,bake(genss,start_rec),checker)
        if(rec=="-"):
            print(n,'fuck')
            continue
        if(rec not in seen_recipes):
            print(n,"NEW!",rec)
            seen_recipes[rec] = n
        else:
            print(n, 'first_seen', seen_recipes[rec])
    return seen_recipes

def is_trans_and_odds(p):
    n = len(p)
    signature = [len(i) for i in p.to_cycles()]
    if signature.count(_sage_const_2 ) == _sage_const_1  and all([(i%_sage_const_2 ==_sage_const_1 ) or (i==_sage_const_2 ) for i,cyc in zip(signature,p.to_cycles())]):
        return True
    else:
        return False

def is_trans_and_odds(p):
    n = len(p)
    signature = [len(i) for i in p.to_cycles()]
    if signature.count(_sage_const_2 ) == _sage_const_1  and all([(i%_sage_const_2 ==_sage_const_1 ) or (i==_sage_const_2 ) for i,cyc in zip(signature,p.to_cycles())]):
        return True
    else:
        return False

def are_adjacent_in_this_cycle(cycle):
    def adj(p):
        if not is_trans_and_odds(p):
            return False
        c = cycle.to_cycles()[_sage_const_0 ]
        p = [q for q in p.to_cycles() if len(q)==_sage_const_2 ][_sage_const_0 ]
        i1, i2 = c.index(p[_sage_const_0 ]), c.index(p[_sage_const_1 ])
        if(abs(i1-i2)==_sage_const_1  or (i1==len(c)-_sage_const_1  and i2==_sage_const_0 ) or (i2==len(c)-_sage_const_1  and i2==_sage_const_0 )):
            return True
        else:
            return False
    return adj

def are_adj_in_this_recipe_cycle(gens,recipe):
    cycle = bake(gens,recipe)
    def adj(p):
        if not is_trans_and_odds(p):
            return False
        c = cycle.to_cycles()[_sage_const_0 ]
        p = [q for q in p.to_cycles() if len(q)==_sage_const_2 ][_sage_const_0 ]
        i1, i2 = c.index(p[_sage_const_0 ]), c.index(p[_sage_const_1 ])
        if(abs(i1-i2)==_sage_const_1  or (i1==len(c)-_sage_const_1  and i2==_sage_const_0 ) or (i2==len(c)-_sage_const_1  and i2==_sage_const_0 )):
            return True
        else:
            return False
    return adj

def find_shortest_recipes_cycle(deltas,cycle_recipe,gen_recs=[],start_rec='',nmin=_sage_const_4 ,nmax=_sage_const_100 ,nstep=_sage_const_1 ):
    if len(gen_recs) != len(deltas):
        gen_recs=list(range(len(deltas)))
    
    seen_recipes = {}
    for n in range(nmin,nmax,nstep):
        basis = [make_pref_by_delta(n,i) for i in deltas]
        genss = [bake(basis,r) for r in gen_recs]
        cycle = bake(genss,cycle_recipe)
        checker = are_adjacent_in_this_cycle(cycle)
        try:
            for rec in seen_recipes.keys():
                if(checker(bake(genss,rec))):
                    print(n, 'first_seen', seen_recipes[rec])
                    raise BreakLoop
        except:
            continue
        rec,perm = bfs(genss,bake(genss,start_rec),checker)
        if(rec=="-"):
            print(n,'fuck')
            continue
        if(rec not in seen_recipes):
            print(n,"NEW!",rec)
            seen_recipes[rec] = n
        else:
            print(n, 'first_seen', seen_recipes[rec])
    return seen_recipes

def find_shortest_recipes_LR(delta,start_rec = '',nmin=_sage_const_4 ,nmax=_sage_const_100 ,nstep=_sage_const_1 ):
    seen_recipes = {}
    for n in range(nmin,nmax,nstep):
        genss = [make_pref_by_delta(n,delta),Prefix(n,n-_sage_const_2 )*Prefix(n,n),Prefix(n,n)*Prefix(n,n-_sage_const_2 )]
        try:
            for rec in seen_recipes.keys():
                if(is_power_good_nminus2(bake(genss,rec))):
                    print(n, 'first_seen', seen_recipes[rec])
                    raise BreakLoop
        except:
            continue
        rc,rec,perm = find_shortest_good_shit_LR(genss,n,start_rec)
        if(rc==-_sage_const_1 ):
            print(n,'fuck')
            continue
        if(rec not in seen_recipes):
            print(n,"NEW!",rec)
            seen_recipes[rec] = n
        else:
            print(n, 'first_seen', seen_recipes[rec])
    return seen_recipes

def check_recipes_LR(delta,recipes,labels,nmin,nmax,nstep):
    ret = {}
    for n in range(nmin,nmax,nstep):
        gens = [make_pref_by_delta(n,delta),Prefix(n,n-_sage_const_1 )*Prefix(n,n),Prefix(n,n)*Prefix(n,n-_sage_const_1 )]
        results = []
        for ind,recipe in enumerate(recipes):
            res = bake(gens,recipe)
            #print(res.to_cycles())
            if(not is_power_good(res)):
                continue
            results.append((labels[ind],find_good_power(res)))
            if(labels[ind] in ret):
                ret[labels[ind]].append(n)
            else:
                ret[labels[ind]] = [n]
        print(n,results)
    return ret

def find_smallest_power(delta,start_rec = '',nmin=_sage_const_4 ,nmax=_sage_const_100 ,nstep=_sage_const_1 ):
    for n in range(nmin,nmax,nstep):
        gens = [make_pref_by_delta(n,delta),Prefix(n,n-_sage_const_1 )*Prefix(n,n),Prefix(n,n)*Prefix(n,n-_sage_const_1 )]
        start = bake(gens,start_rec)
        if(is_power_good(start*bake(gens,'0110'))):
            print(n,'0110')
            continue
        if(is_power_good(start*bake(gens,'0220'))):
            print(n,'0220')
            continue
        cnt=_sage_const_0 
        while(not is_power_good(start) and cnt<_sage_const_5000 ):
            start*=gens[_sage_const_2 ]
            cnt+=_sage_const_1 
        
        if(cnt>=_sage_const_5000 ):
            print(n,'notfound')
            n,rec,per = find_shortest_good_shit_LR(gens,n,start_rec)
            print(n,rec)
        else:
            print(n,cnt,start_rec+'2'*cnt)


def find_conjecture(nmin,nmax,delta=-_sage_const_1 ):
    print("conjectures for r_k r_n"+str(delta)+" r_n")
    print("n\tk's")
    for n in range(nmin,nmax):
        Sn_card = SymmetricGroup(n).cardinality()
        good_ks=[]
        for k in range(_sage_const_2 ,n-_sage_const_1 ):
            gens = [Prefix(n,k),make_pref_by_delta(n,delta),Prefix(n,n)]
            G = PermutationGroup(gens)
            if(Sn_card == G.cardinality()):
                good_ks.append(k)
        print(n,good_ks,sep='\t',flush=True)

def find_conjecture_kplus(nmin,nmax):
    print("conjectures for r_k-1 r_k r_n")
    print("n\tk's")
    for n in range(nmin,nmax):
        Sn_card = SymmetricGroup(n).cardinality()
        good_ks=[]
        for k in range(_sage_const_3 ,n-_sage_const_1 ):
            gens = [Prefix(n,k-_sage_const_1 ),Prefix(n,k),Prefix(n,n)]
            G = PermutationGroup(gens)
            if(Sn_card == G.cardinality()):
                good_ks.append(k)
        print(n,good_ks,sep='\t',flush=True)


def find_conjecture_top(nmax,delta=_sage_const_2 ):
    print('top conjecture for k:',delta)
    print("n\tn-k's")
    for n in range(_sage_const_3 ,nmax):
        Sn_card = SymmetricGroup(n).cardinality()
        good_ks=[]
        for sub in range(_sage_const_1 ,n-_sage_const_1 ):
            gens = [make_pref_by_delta(n,delta),Prefix(n,n-sub),Prefix(n,n)]
            G = PermutationGroup(gens)
            if(Sn_card == G.cardinality()):
                good_ks.append(sub)
        print(n,good_ks,sep='\t')

def tos(p):
    return '"'+''.join([str(i) for i in list(p)])+'"'

def is_n_cycle(p):
    return (len(p) == list(sorted(p.signature()))[_sage_const_0 ])

def is_default_n_cycle(p):
    return p.to_cycles()==[tuple(i+_sage_const_1  for i in range(len(p)))]

def is_transposition(p):
    c=p.to_cycles()
    return list(sorted(c.signature())) == ((len(c)-_sage_const_1 )*[_sage_const_1 ])+[_sage_const_2 ]




def wtf(f):
    return f


def has_adjacent(p):
    p = p.to_cycles()
    if(len(p)>_sage_const_1 ):
        return False
    p=p[_sage_const_0 ]
    n=len(p)
    pairs=[(p[i],p[(i+_sage_const_1 )%n]) for i in range(n)]
    return any([abs(j-i)==_sage_const_1  for i,j in pairs])

def bfs_growth(gens,start):
    seen = set()
    q = Queue()
    q.put((_sage_const_0 ,start))
    ans={}
    while(q.qsize()!=_sage_const_0 ):
        v=q.get()
        for g in gens:
            to=v[_sage_const_1 ]*g
            if(tuple(to) not in seen):
                if v[_sage_const_0 ] in ans:
                    ans[v[_sage_const_0 ]]+=_sage_const_1 
                else:
                    ans[v[_sage_const_0 ]]=_sage_const_1 
                seen.add(tuple(to))
                q.put((v[_sage_const_0 ]+_sage_const_1 ,to))
    return ans

def compute_growth():
    for n in range(_sage_const_8 ,_sage_const_10 ):
        Sn_card = SymmetricGroup(n).cardinality()
        for k in range(_sage_const_2 ,n-_sage_const_1 ):
            gens = [Prefix(n,k),Prefix(n,n-_sage_const_1 ),Prefix(n,n)]
            if(Sn_card != PermutationGroup(gens).cardinality()):
                continue
            d = bfs_growth(gens,Prefix(n,_sage_const_1 ))
            print(n,k,list(dict(bfs_growth(gens,Prefix(n,_sage_const_1 ))).values()))


if __name__=="__main__":
    for n in range(_sage_const_4 ,_sage_const_101 ):
        Sn_card = SymmetricGroup(n).cardinality()
        for b in range(_sage_const_2 ,n):
            for a in range(_sage_const_2 ,b):
                gens = [Prefix(n,a),Prefix(n,b),Prefix(n,n)]
                prefix_group_card = PermutationGroup(gens).cardinality()
                print((a,b,n,Sn_card//prefix_group_card,))
    exit(_sage_const_0 )

    for n in range(_sage_const_6 ,_sage_const_500 ):
        for k in range((n//_sage_const_2 +_sage_const_1  if (n//_sage_const_2 )%_sage_const_2 !=_sage_const_0  else n//_sage_const_2 +_sage_const_2 ),n,_sage_const_2 ):
            print(n,k)
            gens = [Prefix(n,k),Prefix(n,k-_sage_const_1 ),Prefix(n,n)]
            #print('012',bake(gens,'012').to_cycles())
            #print('121',bake(gens,'121').to_cycles())
            #print('021',bake(gens,'021').to_cycles())
            print([i for i in bake(gens,'012012121021').to_cycles() if len(i)>=_sage_const_2 ])
    exit(_sage_const_0 )
    find_conjecture_kplus(_sage_const_4 ,_sage_const_200 )
    exit(_sage_const_0 )
    import sys
    print(sys.argv)
    find_conjecture(_sage_const_6 ,int(float(sys.argv[_sage_const_2 ])),-int(float(sys.argv[_sage_const_1 ])))
    exit(_sage_const_0 )
    # compute_growth()
    # exit(0)
    # find_conjecture(71,151,-11)
    # exit(0)
    for n in range(_sage_const_1 ,_sage_const_20 ):
       print(n,":")
       [print(i.to_cycles()) for i in (Prefix(n,n)*Prefix(n,n-_sage_const_2 )).get_all_powers()]
       print()
    exit(_sage_const_0 )
    find_conjecture_top(_sage_const_101 ,_sage_const_5 )
    exit(_sage_const_0 )
    find_shortest_recipes_general([_sage_const_9 ,-_sage_const_2 ,_sage_const_0 ],is_power_good_nminus2,['0','12','21'],'',_sage_const_6 ,_sage_const_100 ,_sage_const_2 )
    exit(_sage_const_0 )
    for n in range(_sage_const_6 ,_sage_const_20 ,_sage_const_2 ):
        for k in range(_sage_const_2 ,n-_sage_const_3 ,_sage_const_2 ):
            gens = [Prefix(n,k), Prefix(n,n-_sage_const_2 )*Prefix(n,n) , Prefix(n,n)*Prefix(n,n-_sage_const_2 )]
            print(n,k,(bake(gens,"0"+"2"*_sage_const_2 )).to_cycles(),"\n",(bake(gens,"0"+"2"*_sage_const_3 )).to_cycles())
            #print(n,k,[cycle if len(cycle) in (n,2) else len(cycle) for cycle in bake(gens,"1"*(k//2)+"0").to_cycles() if len(cycle)!=1])
    exit(_sage_const_0 )
    k=_sage_const_8 
    find_shortest_recipes_cycle([k,-_sage_const_2 ,_sage_const_0 ],'01111',["0","12","21"],'',_sage_const_7 ,_sage_const_100 ,_sage_const_2 )
    exit(_sage_const_0 )
    for k in range(_sage_const_2 ,_sage_const_40 ,_sage_const_2 ):
        for n in range(k+_sage_const_3 ,_sage_const_100 ,_sage_const_2 ):
            gens = [Prefix(n,k),Prefix(n,n-_sage_const_2 )*Prefix(n,n),Prefix(n,n)*Prefix(n,n-_sage_const_2 )]
            print(n,k,(bake(gens,"0"+(k//_sage_const_2 )*"1")).to_cycles())
            print()
    exit(_sage_const_0 )
    '''
    a=3
    for n in range(2,20,1):
        print(n,[i.signature() for i in (Prefix(n,n-a)*Prefix(n,n)).get_all_powers()])
        print()
    exit(0)
    find_conjecture(101)
    #exit(0)
    n=20
    k=15
    Sn_size=SymmetricGroup(n).cardinality()
    gens = [Prefix(n,k),Prefix(n,n-2),Prefix(n,n)]
    print((gens[1]*gens[2]).to_cycles())
    for l in range(7):
        print(l,(bake(gens,"0"+"12"*l)).to_cycles())
    exit(0)
    our_size=PermutationGroup([gens[1]*gens[2],bake(gens,"0"+"12"*6)**(n-3)]).cardinality()
    
    print((bake(gens,"0"+"12"*6)**(n-3)).to_cycles())
    print(Sn_size,our_size)
    exit(0)
    '''
    
    for n in range(_sage_const_40 ,_sage_const_41 ,_sage_const_2 ):
        rn2 = Prefix(n,n-_sage_const_2 )
        rn = Prefix(n,n)
        gens=[Prefix(n,_sage_const_11 ),Prefix(n,n-_sage_const_2 ),Prefix(n,n)]
        for l in range(_sage_const_6 ):
            print(l,(bake(gens,"0"+"12"*l).to_cycles()))
    exit(_sage_const_0 )
    
    #find_conjecture(101)
    '''
    find_shortest_recipes_LR(9,'',6,100,2)
    for n in range(12,100,2):
        gens = [Prefix(n,9),(Prefix(n,n-2)*Prefix(n,n)),Prefix(n,n)*Prefix(n,n-2)]
        L,R = gens[1], gens[2]
        print(n,(bake(gens,"0111")).to_cycles())
        #print(n, (bake(gens,"010102022")).to_cycles(), [len(i) for i in (R*R*bake(gens,"010102022")*L*L).to_cycles()])
    '''
        #for k in range(3,n-2,2):
        #    gens = [Prefix(n,k),(Prefix(n,n-2)*Prefix(n,n)),Prefix(n,n)*Prefix(n,n-2)]
        #    print(n,k,[i for i in (bake(gens,"0"+"1"*((k-2)//2))).to_cycles() if len(i)%2==0])
'''
def bfs(gens:list[Permutation],init:Permutation,looking_for:Callable[[Permutation],bool]) -> [string]:
    now_layer = {init}
    while(len(now_layer) != 0):
        now
'''

'''
if __name__ == "__main__":
    compute_diameters()
    find_conjecture(101)
    exit(0)
    find_shortest_recipes_LR(4,'',7,50,4)
    exit(0)
    recipe = '01011102222'
    for n in range(13,50,2):
        L, R = Prefix(n,n)*Prefix(n-1,n),Prefix(n-1,n)*Prefix(n,n)
        gens = [Prefix(10,n),L,R]
        print((R**7)*(bake(gens,recipe)**(35))*(L**7).to_cycles())
    exit(0)
'''

