

# This file was *autogenerated* from the file test5.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_10 = Integer(10); _sage_const_100 = Integer(100); _sage_const_50 = Integer(50)
from sage.all import *
from collections import deque, defaultdict
import itertools

def compute_diameter(S, G):
    identity = G.identity()
    visited = {identity: _sage_const_0 }
    queue = deque([identity])

    while queue:
        current = queue.popleft()
        current_dist = visited[current]
        for s in S:
            next_perm = current * s
            if next_perm not in visited:
                visited[next_perm] = current_dist + _sage_const_1 
                queue.append(next_perm)
    return max(visited.values())

def is_prefix_reversal(g, n):
    permuted = [g(i) for i in range(_sage_const_1 , n+_sage_const_1 )]
    for k in range(_sage_const_2 , n+_sage_const_1 ):
        expected = list(range(k, _sage_const_0 , -_sage_const_1 )) + list(range(k+_sage_const_1 , n+_sage_const_1 ))
        if permuted == expected:
            return True
    return False

def canonical_form(triple, G):
    min_rep = None
    triple_list = list(triple)

    for p in G:
        conj_triple = tuple(sorted([p * g * p.inverse() for g in triple_list], key=lambda x: str(x)))
        rep = tuple(str(g) for g in conj_triple)
        if (min_rep is None) or (rep < min_rep):
            min_rep = rep
    return min_rep

def main():
    n = int(input("Enter the value of n: "))
    G = SymmetricGroup(n)
    identity = G.identity()
    perms = list(G)

    # Filter out identity permutations
    non_id_perms = [g for g in perms if g != identity]

    # Generate all 3-element combinations
    combinations_list = list(itertools.combinations(non_id_perms, _sage_const_3 ))
    total = len(combinations_list)
    update_interval = max(_sage_const_1 , total // _sage_const_10 )

    print(f"Total combinations to process: {total}", flush=True)
    print("Starting progress tracking...", flush=True)

    # Dictionary to store conjugacy classes and prefix status
    canonical_classes = defaultdict(bool)
    final_output = {}

    for idx, generators in enumerate(combinations_list):
        if idx % update_interval == _sage_const_0 :
            percent = (idx / total) * _sage_const_100 
            print(f"Progress: {percent:.0f}%", flush=True)

        S = set(generators)
        inv_S = {g**(-_sage_const_1 ) for g in S}
        if S != inv_S:
            continue

        try:
            H = G.subgroup(list(S))
        except:
            continue

        if H != G:
            continue

        is_prefix = all(is_prefix_reversal(g, n) for g in generators)
        cform = canonical_form(generators, G)

        # Update conjugacy class with prefix info
        if is_prefix:
            canonical_classes[cform] = True
        elif cform not in canonical_classes:
            canonical_classes[cform] = False

        # Compute diameter
        diameter = compute_diameter(S, G)

        # Store result for final output
        sorted_generators = sorted(generators, key=lambda x: str(x))
        if cform in final_output:
            if diameter < final_output[cform][_sage_const_1 ]:
                final_output[cform] = (sorted_generators, diameter, canonical_classes[cform])
        else:
            final_output[cform] = (sorted_generators, diameter, canonical_classes[cform])

    print("Progress: 100%", flush=True)

    # Print final results
    print("\nFinal Results:\n" + "-" * _sage_const_50 )
    for cform, (generators, diameter, is_prefix) in final_output.items():
        suffix = " PREFIX!" if is_prefix else ""
        print(f"Triple: {tuple(generators)}, Diameter: {diameter}{suffix}")

if __name__ == "__main__":
    main()

