

# This file was *autogenerated* from the file vis.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_6 = Integer(6); _sage_const_51 = Integer(51); _sage_const_100 = Integer(100); _sage_const_4 = Integer(4)
import math
from sys import stdout

from sage.graphs.distances_all_pairs import diameter
from sage.groups.perm_gps.permgroup import PermutationGroup

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
#from sage.groups.perm_gps.permgroup import PermutationGroup


def is_good_transposition(p):
    n=len(p)
    sign = [len(i) for i in p.to_cycles()]
    sign.sort()
    return (sign[-_sage_const_1 ]==_sage_const_2  and sign.count(_sage_const_1 )==n-_sage_const_2  and any([len(i)==_sage_const_2  and math.gcd(i[_sage_const_1 ]-i[_sage_const_0 ],n)==_sage_const_1  for i in p.to_cycles()]))

def perm_pow(self,a):
        if(a==_sage_const_1 ): return self
        if(a==_sage_const_0 ): return Permutation(self.n)
        if(a%_sage_const_2 ==_sage_const_0 ):
            b=self**(a//_sage_const_2 )
            return b*b
        else:
            return self**(a-_sage_const_1 )*self

def signature(self):
    return list(sorted([len(i) for i in self.to_cycles()]))

def get_all_powers(self):
        perm = self
        perm *= perm
        powers = [self,perm]
        while True:
            perm*=self
            if tuple(self)==tuple(perm):
                break
            powers.append(perm)
        return powers

Permutation.__pow__ = perm_pow
Permutation.get_all_powers = get_all_powers
Permutation.signature = signature

def Prefix(n,k):
    l=[i+_sage_const_1  for i in range(n)]
    l=l[:k][::-_sage_const_1 ]+l[k:]
    return Permutation(list(tuple(l)))

def make_pref_by_delta(n,delta):
    if(delta<_sage_const_0 ):
        return Prefix(n,n+delta)
    elif delta==_sage_const_0 :
        return Prefix(n,n)
    else:
        return Prefix(n,delta)

def check(n,d1,d2):
    r1,r2,rn = make_pref_by_delta(n,d1),make_pref_by_delta(n,d2), Prefix(n,n)
    G_size = PermutationGroup([r1,r2,rn]).cardinality()
    Sn_size = SymmetricGroup(n).cardinality()
    return G_size == Sn_size

if __name__=="__main__":
    d2max=_sage_const_6 
    for d2 in range(_sage_const_1 ,d2max+_sage_const_1 ):
        answers=[list(range(_sage_const_2 ,i)) for i in range(_sage_const_1 ,_sage_const_51 )]
        for n in range(_sage_const_1 ,_sage_const_51 ):
            for d1 in range(_sage_const_2 ,n):
                answers[(n,d1)]=check(n,d1,d2)
                print(check(n,d1,d2),end='')


d={}
rangex=[_sage_const_100 ,_sage_const_0 ]
rangey=[_sage_const_100 ,_sage_const_0 ]
fname='inpn11.txt'
with open(fname,'r') as f:
    for line in f:
        fs=line.index(' ')
        d[int(line[:fs])]=['' if len(i)==_sage_const_0  else int(i.strip()) for i in line[line.index('[')+_sage_const_1 :line.index(']')].split(',')]
        rangey[_sage_const_0 ]=min(rangey[_sage_const_0 ],int(line[:fs]))
        rangey[_sage_const_1 ]=max(rangey[_sage_const_0 ],int(line[:fs]))
        rangex[_sage_const_0 ]=min(rangex[_sage_const_0 ],min(d[int(line[:fs])]))
        rangex[_sage_const_1 ]=max(rangex[_sage_const_0 ],max(d[int(line[:fs])]))


ans=[[] for i in range(rangey[_sage_const_0 ],rangey[_sage_const_1 ]+_sage_const_1 )]
for n in range(rangey[_sage_const_0 ],rangey[_sage_const_1 ]+_sage_const_1 ):
    i=n-rangey[_sage_const_0 ]
    for k in range(rangex[_sage_const_0 ],rangex[_sage_const_1 ]+_sage_const_1 ):
        if k in d[n]:
            ans[i].append(_sage_const_1 )
        else:
            ans[i].append(_sage_const_0 )

ans=ans[::-_sage_const_1 ]


harvest = np.array(ans)


def c(x):
    return {_sage_const_0 :"white",_sage_const_1 :"green"}[x]

fig, ax = plt.subplots()
im = ax.imshow(harvest,cmap="Greens")

y=list(range(rangey[_sage_const_0 ],rangey[_sage_const_1 ]+_sage_const_1 ))
x=list(range(rangex[_sage_const_0 ],rangex[_sage_const_1 ]+_sage_const_1 ))
# Show all ticks and label them with the respective list entries
ax.set_xticks(np.arange(len(x)), labels=x)
ax.set_yticks(np.arange(len(y)), labels=y[::-_sage_const_1 ])

ax.set_xlabel("k")
ax.set_ylabel("n")

# Rotate the tick labels and set their alignment.
# plt.setp(ax.get_xticklabels(), rotation=45, ha="right",
#          rotation_mode="anchor")

# Loop over data dimensions and create text annotations.
# for i in range(len(xy)):
#     for j in range(len(xy)):
#         text = ax.text(j, i, str((i,j)),
#                        ha="center", va="center", color="red")

ax.set_title(f"Does r_k, r_{{n-{fname[_sage_const_4 :fname.index('.')]}}}, r_n generate S_n?")
fig.tight_layout()
plt.show()


